#!/usr/bin/env python3
"""
Solana Wallet Profitability Analyzer
=====================================

A modular Python script for analyzing Solana wallet profitability using the Helius API.
Supports analyzing token swaps (Jupiter/Raydium), calculating ROI/PnL, and identifying
profitable trading patterns.

Features:
- Multi-wallet analysis
- Transaction history fetching via Helius API
- Token swap parsing (Jupiter & Raydium)
- ROI and PnL calculation
- Early bird pattern detection
- Repeat successful trader identification
- Ranked output by profitability

Usage:
    python solana_wallet_analyzer.py --wallets <wallet1> <wallet2> ... --api-key <helius_api_key>
    
    Or with a wallet file:
    python solana_wallet_analyzer.py --wallet-file wallets.txt --api-key <helius_api_key>

Requirements:
    pip install requests python-dotenv

Author: Generated by AI Assistant
License: MIT
"""

import os
import sys
import json
import time
import argparse
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple, Any, Set
from collections import defaultdict
from enum import Enum
import concurrent.futures
from pathlib import Path

# Third-party imports
try:
    import requests
except ImportError:
    print("Error: 'requests' package is required. Install with: pip install requests")
    sys.exit(1)

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


# =============================================================================
# CONFIGURATION & CONSTANTS
# =============================================================================

class Config:
    """Configuration constants for the analyzer."""
    
    # Helius API Configuration
    HELIUS_BASE_URL = "https://mainnet.helius-rpc.com"
    HELIUS_API_VERSION = "v0"
    
    # Rate limiting
    MAX_RETRIES = 3
    RETRY_DELAY = 1  # seconds
    REQUEST_TIMEOUT = 30  # seconds
    
    # Analysis parameters
    EARLY_BIRD_BLOCKS = 10  # Consider "early" if bought within first N blocks
    MIN_TRADES_FOR_PATTERN = 3  # Minimum trades to identify patterns
    PROFITABLE_THRESHOLD = 0.05  # 5% profit considered "win"
    
    # DEX Program IDs
    JUPITER_PROGRAM_ID = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
    RAYDIUM_PROGRAM_ID = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
    RAYDIUM_CONCENTRATED = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"
    
    # Token decimals cache
    DECIMALS_CACHE: Dict[str, int] = {}


# =============================================================================
# DATA CLASSES
# =============================================================================

class TradeType(Enum):
    """Type of trade operation."""
    BUY = "buy"
    SELL = "sell"
    UNKNOWN = "unknown"


class DEXType(Enum):
    """Decentralized exchange type."""
    JUPITER = "jupiter"
    RAYDIUM = "raydium"
    RAYDIUM_CLMM = "raydium_clmm"
    UNKNOWN = "unknown"


@dataclass
class TokenTransfer:
    """Represents a token transfer in a transaction."""
    mint: str
    amount: float
    decimals: int
    from_address: str
    to_address: str
    is_native: bool = False
    
    @property
    def normalized_amount(self) -> float:
        """Return amount normalized by decimals."""
        return self.amount / (10 ** self.decimals)


@dataclass
class TokenSwap:
    """Represents a token swap transaction."""
    signature: str
    timestamp: datetime
    dex: DEXType
    token_in: TokenTransfer
    token_out: TokenTransfer
    trade_type: TradeType
    wallet: str
    slot: int
    block_time: int
    
    # Calculated fields
    price: float = 0.0
    value_usd: float = 0.0
    
    def __post_init__(self):
        """Calculate price after initialization."""
        if self.token_out.normalized_amount > 0:
            self.price = self.token_in.normalized_amount / self.token_out.normalized_amount


@dataclass
class Position:
    """Tracks a trading position for a specific token."""
    token_mint: str
    token_symbol: str = ""
    entry_price: float = 0.0
    total_bought: float = 0.0
    total_spent: float = 0.0
    total_sold: float = 0.0
    total_received: float = 0.0
    remaining_quantity: float = 0.0
    first_buy_slot: Optional[int] = None
    last_buy_time: Optional[datetime] = None
    
    @property
    def avg_buy_price(self) -> float:
        """Calculate average buy price."""
        if self.total_bought > 0:
            return self.total_spent / self.total_bought
        return 0.0
    
    @property
    def realized_pnl(self) -> float:
        """Calculate realized PnL (from completed trades)."""
        return self.total_received - (self.total_sold * self.avg_buy_price)
    
    @property
    def unrealized_pnl(self, current_price: float = 0) -> float:
        """Calculate unrealized PnL (from remaining position)."""
        if current_price > 0:
            return self.remaining_quantity * (current_price - self.avg_buy_price)
        return 0.0


@dataclass
class WalletAnalysis:
    """Complete analysis results for a wallet."""
    wallet_address: str
    total_trades: int = 0
    profitable_trades: int = 0
    losing_trades: int = 0
    total_pnl: float = 0.0
    total_roi: float = 0.0
    win_rate: float = 0.0
    avg_trade_size: float = 0.0
    
    # Detailed tracking
    swaps: List[TokenSwap] = field(default_factory=list)
    positions: Dict[str, Position] = field(default_factory=dict)
    
    # Pattern analysis
    early_bird_count: int = 0
    early_bird_success_rate: float = 0.0
    is_repeat_winner: bool = False
    consistent_profit_score: float = 0.0
    
    # Metadata
    first_trade_time: Optional[datetime] = None
    last_trade_time: Optional[datetime] = None
    analysis_timestamp: datetime = field(default_factory=datetime.now)
    
    def calculate_summary_stats(self):
        """Calculate summary statistics after all trades are processed."""
        if self.total_trades > 0:
            self.win_rate = self.profitable_trades / self.total_trades
            
        # Calculate total PnL from positions
        self.total_pnl = sum(pos.realized_pnl for pos in self.positions.values())
        
        # Calculate ROI
        total_invested = sum(pos.total_spent for pos in self.positions.values())
        if total_invested > 0:
            self.total_roi = self.total_pnl / total_invested
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert analysis to dictionary for JSON serialization."""
        return {
            "wallet_address": self.wallet_address,
            "total_trades": self.total_trades,
            "profitable_trades": self.profitable_trades,
            "losing_trades": self.losing_trades,
            "total_pnl": round(self.total_pnl, 6),
            "total_roi": round(self.total_roi, 4),
            "win_rate": round(self.win_rate, 4),
            "avg_trade_size": round(self.avg_trade_size, 6),
            "early_bird_count": self.early_bird_count,
            "early_bird_success_rate": round(self.early_bird_success_rate, 4),
            "is_repeat_winner": self.is_repeat_winner,
            "consistent_profit_score": round(self.consistent_profit_score, 4),
            "first_trade_time": self.first_trade_time.isoformat() if self.first_trade_time else None,
            "last_trade_time": self.last_trade_time.isoformat() if self.last_trade_time else None,
            "positions": {
                mint: {
                    "token_mint": pos.token_mint,
                    "total_bought": pos.total_bought,
                    "total_sold": pos.total_sold,
                    "realized_pnl": pos.realized_pnl,
                    "avg_buy_price": pos.avg_buy_price,
                    "remaining": pos.remaining_quantity
                }
                for mint, pos in self.positions.items()
            }
        }


# =============================================================================
# HELIUS API CLIENT
# =============================================================================

class HeliusClient:
    """
    Client for interacting with the Helius API.
    Handles rate limiting, retries, and pagination.
    """
    
    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = Config.HELIUS_BASE_URL
        self.session = requests.Session()
        self.logger = logging.getLogger(__name__)
        
    def _make_request(self, method: str, params: Dict = None) -> Dict:
        """
        Make a request to the Helius API with retry logic.
        
        Args:
            method: RPC method name
            params: Request parameters
            
        Returns:
            JSON response data
            
        Raises:
            requests.RequestException: If all retries fail
        """
        url = f"{self.base_url}/?api-key={self.api_key}"
        payload = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": method,
            "params": params or []
        }
        
        for attempt in range(Config.MAX_RETRIES):
            try:
                response = self.session.post(
                    url,
                    json=payload,
                    timeout=Config.REQUEST_TIMEOUT
                )
                response.raise_for_status()
                data = response.json()
                
                if "error" in data:
                    raise Exception(f"API Error: {data['error']}")
                    
                return data.get("result", {})
                
            except requests.RequestException as e:
                self.logger.warning(f"Request failed (attempt {attempt + 1}): {e}")
                if attempt < Config.MAX_RETRIES - 1:
                    time.sleep(Config.RETRY_DELAY * (attempt + 1))
                else:
                    raise
                    
        return {}
    
    def get_signatures_for_address(
        self,
        address: str,
        limit: int = 100,
        before: Optional[str] = None,
        until: Optional[str] = None
    ) -> List[Dict]:
        """
        Fetch transaction signatures for an address.
        
        Args:
            address: Wallet or program address
            limit: Maximum signatures to fetch (max 1000)
            before: Fetch signatures before this signature
            until: Fetch signatures until this signature
            
        Returns:
            List of signature data
        """
        params = {
            "limit": min(limit, 1000),
            "commitment": "confirmed"
        }
        if before:
            params["before"] = before
        if until:
            params["until"] = until
            
        result = self._make_request(
            "getSignaturesForAddress",
            [address, params]
        )
        return result if isinstance(result, list) else []
    
    def get_transaction(self, signature: str, max_supported_transaction_version: int = 0) -> Optional[Dict]:
        """
        Fetch detailed transaction data.
        
        Args:
            signature: Transaction signature
            max_supported_transaction_version: Maximum transaction version to support
            
        Returns:
            Transaction data or None if not found
        """
        params = {
            "encoding": "jsonParsed",
            "maxSupportedTransactionVersion": max_supported_transaction_version,
            "commitment": "confirmed"
        }
        
        result = self._make_request("getTransaction", [signature, params])
        return result
    
    def get_account_info(self, address: str) -> Optional[Dict]:
        """
        Fetch account information.
        
        Args:
            address: Account address
            
        Returns:
            Account data or None if not found
        """
        params = {
            "encoding": "jsonParsed",
            "commitment": "confirmed"
        }
        
        result = self._make_request("getAccountInfo", [address, params])
        return result.get("value") if result else None
    
    def get_token_metadata(self, mint: str) -> Dict:
        """
        Fetch token metadata using Helius enhanced API.
        
        Args:
            mint: Token mint address
            
        Returns:
            Token metadata
        """
        # Try to get from enhanced API
        url = f"https://mainnet.helius-rpc.com/?api-key={self.api_key}"
        payload = {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "getAsset",
            "params": {"id": mint}
        }
        
        try:
            response = self.session.post(url, json=payload, timeout=Config.REQUEST_TIMEOUT)
            data = response.json()
            return data.get("result", {})
        except Exception as e:
            self.logger.warning(f"Failed to fetch metadata for {mint}: {e}")
            return {}
    
    def get_all_transactions(
        self,
        address: str,
        limit: Optional[int] = None,
        days_back: Optional[int] = None
    ) -> List[Dict]:
        """
        Fetch all transactions for an address with pagination.
        
        Args:
            address: Wallet address
            limit: Maximum transactions to fetch (None for all)
            days_back: Only fetch transactions from last N days
            
        Returns:
            List of transaction signatures
        """
        all_signatures = []
        before = None
        batch_size = 100
        
        # Calculate cutoff timestamp if days_back specified
        cutoff_time = None
        if days_back:
            cutoff_time = int((datetime.now() - timedelta(days=days_back)).timestamp())
        
        while True:
            # Check if we've reached the limit
            if limit and len(all_signatures) >= limit:
                break
                
            current_batch_size = min(batch_size, limit - len(all_signatures)) if limit else batch_size
            
            signatures = self.get_signatures_for_address(
                address,
                limit=current_batch_size,
                before=before
            )
            
            if not signatures:
                break
                
            # Check time cutoff
            if cutoff_time:
                valid_signatures = [
                    sig for sig in signatures 
                    if sig.get("blockTime", 0) > cutoff_time
                ]
                all_signatures.extend(valid_signatures)
                
                # If we filtered some out, we've reached the cutoff
                if len(valid_signatures) < len(signatures):
                    break
            else:
                all_signatures.extend(signatures)
            
            # Set before for next iteration
            before = signatures[-1].get("signature")
            
            # Stop if we got fewer than requested
            if len(signatures) < current_batch_size:
                break
                
        return all_signatures[:limit] if limit else all_signatures


# =============================================================================
# TRANSACTION PARSER
# =============================================================================

class TransactionParser:
    """
    Parser for Solana transactions.
    Extracts token swaps, transfers, and relevant metadata.
    """
    
    # Known DEX program IDs
    DEX_PROGRAMS = {
        Config.JUPITER_PROGRAM_ID: DEXType.JUPITER,
        Config.RAYDIUM_PROGRAM_ID: DEXType.RAYDIUM,
        Config.RAYDIUM_CONCENTRATED: DEXType.RAYDIUM_CLMM,
    }
    
    # Wrapped SOL mint
    WRAPPED_SOL = "So11111111111111111111111111111111111111112"
    
    def __init__(self, client: HeliusClient):
        self.client = client
        self.logger = logging.getLogger(__name__)
        
    def detect_dex(self, transaction: Dict) -> DEXType:
        """
        Detect which DEX was used in the transaction.
        
        Args:
            transaction: Transaction data from Helius
            
        Returns:
            DEX type
        """
        account_keys = self._get_account_keys(transaction)
        
        for program_id, dex_type in self.DEX_PROGRAMS.items():
            if program_id in account_keys:
                return dex_type
                
        # Check inner instructions for program calls
        meta = transaction.get("meta", {})
        inner_instructions = meta.get("innerInstructions", [])
        
        for inner in inner_instructions:
            for instruction in inner.get("instructions", []):
                program_id = instruction.get("programId", "")
                if program_id in self.DEX_PROGRAMS:
                    return self.DEX_PROGRAMS[program_id]
                    
        return DEXType.UNKNOWN
    
    def _get_account_keys(self, transaction: Dict) -> List[str]:
        """Extract account keys from transaction."""
        tx_data = transaction.get("transaction", {})
        message = tx_data.get("message", {})
        
        account_keys = []
        
        # Handle both legacy and versioned transactions
        if "accountKeys" in message:
            account_keys = [
                acc.get("pubkey") if isinstance(acc, dict) else acc
                for acc in message.get("accountKeys", [])
            ]
        elif "accounts" in message:
            account_keys = message.get("accounts", [])
            
        return account_keys
    
    def parse_token_transfers(self, transaction: Dict, wallet: str) -> List[TokenTransfer]:
        """
        Parse all token transfers from a transaction.
        
        Args:
            transaction: Transaction data
            wallet: Wallet address being analyzed
            
        Returns:
            List of token transfers
        """
        transfers = []
        meta = transaction.get("meta", {})
        
        # Get pre and post token balances
        pre_balances = {b["mint"]: b for b in meta.get("preTokenBalances", [])}
        post_balances = {b["mint"]: b for b in meta.get("postTokenBalances", [])}
        
        # Parse from token balance changes
        all_mints = set(pre_balances.keys()) | set(post_balances.keys())
        
        for mint in all_mints:
            pre = pre_balances.get(mint, {})
            post = post_balances.get(mint, {})
            
            pre_amount = float(pre.get("uiTokenAmount", {}).get("amount", 0))
            post_amount = float(post.get("uiTokenAmount", {}).get("amount", 0))
            decimals = pre.get("uiTokenAmount", {}).get("decimals") or post.get("uiTokenAmount", {}).get("decimals", 0)
            
            # Find owner in balance data
            pre_owner = pre.get("owner", "")
            post_owner = post.get("owner", "")
            
            amount_change = post_amount - pre_amount
            
            if amount_change != 0:
                transfers.append(TokenTransfer(
                    mint=mint,
                    amount=abs(amount_change),
                    decimals=decimals,
                    from_address=pre_owner if amount_change < 0 else "",
                    to_address=post_owner if amount_change > 0 else "",
                    is_native=(mint == self.WRAPPED_SOL)
                ))
        
        # Also check inner instructions for transfers
        inner_instructions = meta.get("innerInstructions", [])
        for inner in inner_instructions:
            for instruction in inner.get("instructions", []):
                parsed = instruction.get("parsed", {})
                if parsed.get("type") == "transfer":
                    info = parsed.get("info", {})
                    # Handle both token and SOL transfers
                    if "mint" in info:
                        transfers.append(TokenTransfer(
                            mint=info.get("mint"),
                            amount=float(info.get("amount", 0)),
                            decimals=int(info.get("decimals", 0)),
                            from_address=info.get("authority", info.get("source", "")),
                            to_address=info.get("destination", ""),
                            is_native=(info.get("mint") == self.WRAPPED_SOL)
                        ))
        
        return transfers
    
    def parse_swap(
        self,
        transaction: Dict,
        signature: str,
        wallet: str
    ) -> Optional[TokenSwap]:
        """
        Parse a token swap from a transaction.
        
        Args:
            transaction: Transaction data from Helius
            signature: Transaction signature
            wallet: Wallet address
            
        Returns:
            TokenSwap object or None if not a valid swap
        """
        try:
            # Detect DEX
            dex = self.detect_dex(transaction)
            if dex == DEXType.UNKNOWN:
                return None
            
            # Get transaction metadata
            block_time = transaction.get("blockTime", 0)
            slot = transaction.get("slot", 0)
            timestamp = datetime.fromtimestamp(block_time)
            
            # Parse token transfers
            transfers = self.parse_token_transfers(transaction, wallet)
            
            if len(transfers) < 2:
                return None
            
            # Determine which transfers involve the wallet
            wallet_transfers = [
                t for t in transfers
                if wallet in [t.from_address, t.to_address]
            ]
            
            if len(wallet_transfers) < 2:
                return None
            
            # Classify as buy or sell based on SOL movement
            # Buy: SOL out, token in
            # Sell: token out, SOL in
            sol_transfers = [t for t in wallet_transfers if t.is_native]
            token_transfers = [t for t in wallet_transfers if not t.is_native]
            
            if not sol_transfers or not token_transfers:
                # Try to determine from transfer direction
                outgoing = [t for t in wallet_transfers if t.from_address == wallet]
                incoming = [t for t in wallet_transfers if t.to_address == wallet]
                
                if len(outgoing) == 1 and len(incoming) == 1:
                    token_in = incoming[0]
                    token_out = outgoing[0]
                    
                    # Determine trade type
                    if token_out.is_native:
                        trade_type = TradeType.BUY
                    elif token_in.is_native:
                        trade_type = TradeType.SELL
                    else:
                        trade_type = TradeType.UNKNOWN
                        
                    return TokenSwap(
                        signature=signature,
                        timestamp=timestamp,
                        dex=dex,
                        token_in=token_in,
                        token_out=token_out,
                        trade_type=trade_type,
                        wallet=wallet,
                        slot=slot,
                        block_time=block_time
                    )
                return None
            
            # Standard SOL-based swap
            sol_transfer = sol_transfers[0]
            token_transfer = token_transfers[0]
            
            if sol_transfer.from_address == wallet:
                # SOL leaving wallet = BUY
                token_in = token_transfer
                token_out = sol_transfer
                trade_type = TradeType.BUY
            else:
                # SOL entering wallet = SELL
                token_in = sol_transfer
                token_out = token_transfer
                trade_type = TradeType.SELL
            
            return TokenSwap(
                signature=signature,
                timestamp=timestamp,
                dex=dex,
                token_in=token_in,
                token_out=token_out,
                trade_type=trade_type,
                wallet=wallet,
                slot=slot,
                block_time=block_time
            )
            
        except Exception as e:
            self.logger.debug(f"Failed to parse swap {signature}: {e}")
            return None
    
    def get_token_decimals(self, mint: str) -> int:
        """Get token decimals, using cache when available."""
        if mint in Config.DECIMALS_CACHE:
            return Config.DECIMALS_CACHE[mint]
        
        # Default to 9 for SOL, 6 for most tokens
        default = 9 if mint == self.WRAPPED_SOL else 6
        
        try:
            account_info = self.client.get_account_info(mint)
            if account_info:
                data = account_info.get("data", [])
                if data and len(data) > 0:
                    parsed = data[0] if isinstance(data, list) else data
                    if isinstance(parsed, dict):
                        decimals = parsed.get("parsed", {}).get("info", {}).get("decimals")
                        if decimals is not None:
                            Config.DECIMALS_CACHE[mint] = decimals
                            return decimals
        except Exception as e:
            self.logger.debug(f"Failed to get decimals for {mint}: {e}")
        
        Config.DECIMALS_CACHE[mint] = default
        return default


# =============================================================================
# PROFITABILITY ANALYZER
# =============================================================================

class ProfitabilityAnalyzer:
    """
    Analyzes wallet trading profitability.
    Calculates PnL, ROI, and identifies patterns.
    """
    
    def __init__(self, client: HeliusClient, parser: TransactionParser):
        self.client = client
        self.parser = parser
        self.logger = logging.getLogger(__name__)
        
    def analyze_wallet(
        self,
        wallet: str,
        days_back: Optional[int] = None,
        tx_limit: Optional[int] = None
    ) -> WalletAnalysis:
        """
        Perform complete profitability analysis on a wallet.
        
        Args:
            wallet: Wallet address
            days_back: Only analyze transactions from last N days
            tx_limit: Maximum transactions to analyze
            
        Returns:
            WalletAnalysis object with complete analysis
        """
        analysis = WalletAnalysis(wallet_address=wallet)
        
        # Fetch all transaction signatures
        self.logger.info(f"Fetching transactions for {wallet}...")
        signatures = self.client.get_all_transactions(wallet, tx_limit, days_back)
        
        if not signatures:
            self.logger.warning(f"No transactions found for {wallet}")
            return analysis
        
        self.logger.info(f"Found {len(signatures)} transactions, analyzing...")
        
        # Process each transaction
        for sig_data in signatures:
            signature = sig_data.get("signature")
            block_time = sig_data.get("blockTime", 0)
            
            if not signature:
                continue
            
            # Update time range
            tx_time = datetime.fromtimestamp(block_time)
            if analysis.first_trade_time is None or tx_time < analysis.first_trade_time:
                analysis.first_trade_time = tx_time
            if analysis.last_trade_time is None or tx_time > analysis.last_trade_time:
                analysis.last_trade_time = tx_time
            
            # Fetch full transaction
            try:
                tx = self.client.get_transaction(signature)
                if not tx:
                    continue
                    
                # Parse swap
                swap = self.parser.parse_swap(tx, signature, wallet)
                if swap:
                    analysis.swaps.append(swap)
                    self._process_swap(analysis, swap)
                    
            except Exception as e:
                self.logger.debug(f"Failed to process transaction {signature}: {e}")
                continue
        
        # Calculate final statistics
        analysis.calculate_summary_stats()
        
        # Analyze patterns
        self._analyze_early_bird_patterns(analysis)
        self._analyze_consistency(analysis)
        
        return analysis
    
    def _process_swap(self, analysis: WalletAnalysis, swap: TokenSwap):
        """Process a swap and update analysis."""
        analysis.total_trades += 1
        
        # Get or create position for the token
        token_mint = swap.token_out.mint if swap.trade_type == TradeType.BUY else swap.token_in.mint
        
        if token_mint not in analysis.positions:
            analysis.positions[token_mint] = Position(token_mint=token_mint)
        
        position = analysis.positions[token_mint]
        
        if swap.trade_type == TradeType.BUY:
            # Buying token
            amount_bought = swap.token_out.normalized_amount
            cost = swap.token_in.normalized_amount
            
            position.total_bought += amount_bought
            position.total_spent += cost
            position.remaining_quantity += amount_bought
            
            if position.first_buy_slot is None:
                position.first_buy_slot = swap.slot
            position.last_buy_time = swap.timestamp
            
        elif swap.trade_type == TradeType.SELL:
            # Selling token
            amount_sold = swap.token_out.normalized_amount
            proceeds = swap.token_in.normalized_amount
            
            position.total_sold += amount_sold
            position.total_received += proceeds
            position.remaining_quantity = max(0, position.remaining_quantity - amount_sold)
            
            # Determine if profitable
            if position.avg_buy_price > 0:
                sell_price = proceeds / amount_sold if amount_sold > 0 else 0
                profit_ratio = (sell_price - position.avg_buy_price) / position.avg_buy_price
                
                if profit_ratio > Config.PROFITABLE_THRESHOLD:
                    analysis.profitable_trades += 1
                elif profit_ratio < -Config.PROFITABLE_THRESHOLD:
                    analysis.losing_trades += 1
    
    def _analyze_early_bird_patterns(self, analysis: WalletAnalysis):
        """
        Analyze early bird patterns (buying tokens early).
        
        A wallet is considered an "early bird" if it buys tokens
        within the first N blocks of their existence.
        """
        early_bird_wins = 0
        early_bird_total = 0
        
        for swap in analysis.swaps:
            if swap.trade_type != TradeType.BUY:
                continue
            
            # Check if this is an early purchase
            # We need to compare against token creation slot
            # For now, we'll use a heuristic based on position first buy
            position = analysis.positions.get(swap.token_out.mint)
            if position and position.first_buy_slot:
                blocks_since_creation = swap.slot - position.first_buy_slot
                
                if blocks_since_creation <= Config.EARLY_BIRD_BLOCKS:
                    early_bird_total += 1
                    
                    # Check if this early buy was profitable
                    if position.realized_pnl > 0:
                        early_bird_wins += 1
        
        analysis.early_bird_count = early_bird_total
        if early_bird_total > 0:
            analysis.early_bird_success_rate = early_bird_wins / early_bird_total
    
    def _analyze_consistency(self, analysis: WalletAnalysis):
        """
        Analyze trading consistency and identify repeat winners.
        
        Consistent traders have:
        - High win rate (>60%)
        - Multiple profitable trades
        - Positive overall PnL
        """
        if analysis.total_trades < Config.MIN_TRADES_FOR_PATTERN:
            return
        
        # Calculate consistency score
        win_rate_score = analysis.win_rate
        volume_score = min(analysis.total_trades / 50, 1.0)  # Normalize to 50 trades
        pnl_score = min(max(analysis.total_roi / 1.0, -1.0), 1.0)  # Normalize to 100% ROI
        
        analysis.consistent_profit_score = (
            win_rate_score * 0.4 +
            volume_score * 0.2 +
            max(pnl_score, 0) * 0.4
        )
        
        # Mark as repeat winner if criteria met
        if (analysis.win_rate >= 0.6 and 
            analysis.profitable_trades >= Config.MIN_TRADES_FOR_PATTERN and
            analysis.total_pnl > 0):
            analysis.is_repeat_winner = True
    
    def rank_wallets(self, analyses: List[WalletAnalysis]) -> List[WalletAnalysis]:
        """
        Rank wallets by profitability.
        
        Ranking criteria (weighted):
        - Total PnL (30%)
        - ROI (25%)
        - Win rate (20%)
        - Consistency score (15%)
        - Early bird success (10%)
        
        Args:
            analyses: List of wallet analyses
            
        Returns:
            Sorted list (highest ranked first)
        """
        def calculate_score(a: WalletAnalysis) -> float:
            # Normalize metrics to 0-1 scale
            max_pnl = max((x.total_pnl for x in analyses), default=1) or 1
            max_roi = max((x.total_roi for x in analyses), default=1) or 1
            
            pnl_score = max(a.total_pnl, 0) / max_pnl if max_pnl > 0 else 0
            roi_score = max(a.total_roi, 0) / max_roi if max_roi > 0 else 0
            
            return (
                pnl_score * 0.30 +
                roi_score * 0.25 +
                a.win_rate * 0.20 +
                a.consistent_profit_score * 0.15 +
                a.early_bird_success_rate * 0.10
            )
        
        return sorted(analyses, key=calculate_score, reverse=True)


# =============================================================================
# OUTPUT FORMATTERS
# =============================================================================

class OutputFormatter:
    """Formats and outputs analysis results."""
    
    @staticmethod
    def format_console(analyses: List[WalletAnalysis], verbose: bool = False) -> str:
        """Format results for console output."""
        lines = []
        lines.append("=" * 100)
        lines.append("SOLANA WALLET PROFITABILITY ANALYSIS")
        lines.append("=" * 100)
        lines.append("")
        
        for i, analysis in enumerate(analyses, 1):
            lines.append(f"#{i} Wallet: {analysis.wallet_address}")
            lines.append("-" * 100)
            lines.append(f"  Total Trades:      {analysis.total_trades}")
            lines.append(f"  Profitable Trades: {analysis.profitable_trades}")
            lines.append(f"  Losing Trades:     {analysis.losing_trades}")
            lines.append(f"  Win Rate:          {analysis.win_rate:.2%}")
            lines.append(f"  Total PnL:         {analysis.total_pnl:.6f} SOL")
            lines.append(f"  Total ROI:         {analysis.total_roi:.2%}")
            lines.append(f"  Avg Trade Size:    {analysis.avg_trade_size:.6f} SOL")
            lines.append("")
            lines.append(f"  Early Bird Trades: {analysis.early_bird_count}")
            lines.append(f"  Early Bird Success: {analysis.early_bird_success_rate:.2%}")
            lines.append(f"  Repeat Winner:     {'Yes' if analysis.is_repeat_winner else 'No'}")
            lines.append(f"  Consistency Score: {analysis.consistent_profit_score:.4f}")
            
            if analysis.first_trade_time:
                lines.append(f"  First Trade:       {analysis.first_trade_time.strftime('%Y-%m-%d %H:%M')}")
            if analysis.last_trade_time:
                lines.append(f"  Last Trade:        {analysis.last_trade_time.strftime('%Y-%m-%d %H:%M')}")
            
            if verbose and analysis.positions:
                lines.append("")
                lines.append("  Top Positions:")
                sorted_positions = sorted(
                    analysis.positions.values(),
                    key=lambda p: abs(p.realized_pnl),
                    reverse=True
                )[:5]
                
                for pos in sorted_positions:
                    lines.append(f"    {pos.token_mint[:20]}...")
                    lines.append(f"      Bought: {pos.total_bought:.4f} | Sold: {pos.total_sold:.4f}")
                    lines.append(f"      PnL: {pos.realized_pnl:.6f} SOL")
                    lines.append(f"      Avg Buy: {pos.avg_buy_price:.8f}")
            
            lines.append("")
        
        return "\n".join(lines)
    
    @staticmethod
    def format_json(analyses: List[WalletAnalysis]) -> str:
        """Format results as JSON."""
        data = {
            "analysis_timestamp": datetime.now().isoformat(),
            "total_wallets_analyzed": len(analyses),
            "rankings": [a.to_dict() for a in analyses]
        }
        return json.dumps(data, indent=2)
    
    @staticmethod
    def format_csv(analyses: List[WalletAnalysis]) -> str:
        """Format results as CSV."""
        lines = [
            "rank,wallet_address,total_trades,profitable_trades,losing_trades,win_rate,total_pnl,total_roi,avg_trade_size,early_bird_count,early_bird_success_rate,is_repeat_winner,consistency_score"
        ]
        
        for i, a in enumerate(analyses, 1):
            lines.append(
                f"{i},{a.wallet_address},{a.total_trades},{a.profitable_trades},"
                f"{a.losing_trades},{a.win_rate:.4f},{a.total_pnl:.6f},"
                f"{a.total_roi:.4f},{a.avg_trade_size:.6f},{a.early_bird_count},"
                f"{a.early_bird_success_rate:.4f},{1 if a.is_repeat_winner else 0},"
                f"{a.consistent_profit_score:.4f}"
            )
        
        return "\n".join(lines)


# =============================================================================
# MAIN APPLICATION
# =============================================================================

def setup_logging(verbose: bool = False):
    """Configure logging."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )


def load_wallets_from_file(filepath: str) -> List[str]:
    """Load wallet addresses from a file (one per line)."""
    wallets = []
    path = Path(filepath)
    
    if not path.exists():
        raise FileNotFoundError(f"Wallet file not found: {filepath}")
    
    with open(path, 'r') as f:
        for line in f:
            wallet = line.strip()
            if wallet and not wallet.startswith('#'):
                wallets.append(wallet)
    
    return wallets


def validate_wallet_address(address: str) -> bool:
    """Basic validation for Solana wallet addresses."""
    # Solana addresses are base58-encoded and 32-44 characters
    if not address or len(address) < 32 or len(address) > 44:
        return False
    # Basic base58 check (alphanumeric excluding 0, O, I, l)
    valid_chars = set('123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz')
    return all(c in valid_chars for c in address)


def main():
    """Main entry point for the analyzer."""
    parser = argparse.ArgumentParser(
        description="Analyze Solana wallet profitability using Helius API",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Analyze single wallet
  python solana_wallet_analyzer.py --wallets 7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU --api-key YOUR_API_KEY
  
  # Analyze multiple wallets
  python solana_wallet_analyzer.py --wallets WALLET1 WALLET2 WALLET3 --api-key YOUR_API_KEY
  
  # Load wallets from file
  python solana_wallet_analyzer.py --wallet-file wallets.txt --api-key YOUR_API_KEY
  
  # Limit to recent activity and output as JSON
  python solana_wallet_analyzer.py --wallets WALLET1 --days-back 30 --output json --api-key YOUR_API_KEY
        """
    )
    
    # Input options
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        '--wallets',
        nargs='+',
        help='One or more wallet addresses to analyze'
    )
    input_group.add_argument(
        '--wallet-file',
        help='File containing wallet addresses (one per line)'
    )
    
    # API configuration
    parser.add_argument(
        '--api-key',
        default=os.getenv('HELIUS_API_KEY'),
        help='Helius API key (or set HELIUS_API_KEY env var)'
    )
    
    # Analysis options
    parser.add_argument(
        '--days-back',
        type=int,
        help='Only analyze transactions from last N days'
    )
    parser.add_argument(
        '--tx-limit',
        type=int,
        help='Maximum transactions to analyze per wallet'
    )
    parser.add_argument(
        '--parallel',
        type=int,
        default=3,
        help='Number of parallel workers (default: 3)'
    )
    
    # Output options
    parser.add_argument(
        '--output',
        choices=['console', 'json', 'csv'],
        default='console',
        help='Output format (default: console)'
    )
    parser.add_argument(
        '--output-file',
        help='Save output to file instead of stdout'
    )
    parser.add_argument(
        '--verbose',
        '-v',
        action='store_true',
        help='Enable verbose logging and output'
    )
    
    args = parser.parse_args()
    
    # Setup logging
    setup_logging(args.verbose)
    logger = logging.getLogger(__name__)
    
    # Validate API key
    if not args.api_key:
        logger.error("Helius API key is required. Use --api-key or set HELIUS_API_KEY env var.")
        sys.exit(1)
    
    # Load wallets
    try:
        if args.wallets:
            wallets = args.wallets
        else:
            wallets = load_wallets_from_file(args.wallet_file)
    except FileNotFoundError as e:
        logger.error(str(e))
        sys.exit(1)
    
    # Validate wallet addresses
    valid_wallets = []
    for wallet in wallets:
        if validate_wallet_address(wallet):
            valid_wallets.append(wallet)
        else:
            logger.warning(f"Invalid wallet address skipped: {wallet}")
    
    if not valid_wallets:
        logger.error("No valid wallet addresses provided.")
        sys.exit(1)
    
    logger.info(f"Analyzing {len(valid_wallets)} wallet(s)...")
    
    # Initialize components
    client = HeliusClient(args.api_key)
    tx_parser = TransactionParser(client)
    analyzer = ProfitabilityAnalyzer(client, tx_parser)
    
    # Analyze wallets
    analyses = []
    
    def analyze_single(wallet: str) -> WalletAnalysis:
        try:
            return analyzer.analyze_wallet(
                wallet,
                days_back=args.days_back,
                tx_limit=args.tx_limit
            )
        except Exception as e:
            logger.error(f"Failed to analyze {wallet}: {e}")
            return WalletAnalysis(wallet_address=wallet)
    
    # Use parallel processing for multiple wallets
    if len(valid_wallets) > 1 and args.parallel > 1:
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.parallel) as executor:
            analyses = list(executor.map(analyze_single, valid_wallets))
    else:
        for wallet in valid_wallets:
            analyses.append(analyze_single(wallet))
    
    # Rank wallets
    ranked_analyses = analyzer.rank_wallets(analyses)
    
    # Format output
    formatter = OutputFormatter()
    
    if args.output == 'json':
        output = formatter.format_json(ranked_analyses)
    elif args.output == 'csv':
        output = formatter.format_csv(ranked_analyses)
    else:
        output = formatter.format_console(ranked_analyses, verbose=args.verbose)
    
    # Write or print output
    if args.output_file:
        with open(args.output_file, 'w') as f:
            f.write(output)
        logger.info(f"Results saved to {args.output_file}")
    else:
        print(output)
    
    # Summary statistics
    profitable_wallets = sum(1 for a in analyses if a.total_pnl > 0)
    repeat_winners = sum(1 for a in analyses if a.is_repeat_winner)
    
    logger.info("=" * 50)
    logger.info(f"Analysis complete!")
    logger.info(f"  Wallets analyzed: {len(analyses)}")
    logger.info(f"  Profitable wallets: {profitable_wallets}")
    logger.info(f"  Repeat winners: {repeat_winners}")
    logger.info("=" * 50)


if __name__ == "__main__":
    main()
